upload_johnny:
	scp schoogle_api_johnny.py reichmanj@perlman.mathcs.carleton.edu:/var/www/html/cs257/reichmanj/assignments-user-Muyang/webapp



run_johnny:
	python3 schoogle_api_johnny.py perlman.mathcs.carleton.edu 5120