upload_big:
	scp -r ../webapp reichmanj@perlman.mathcs.carleton.edu:/var/www/html/cs257/reichmanj/assignments-user-Muyang


upload_small:
	scp -r ../webapp/templates reichmanj@perlman.mathcs.carleton.edu:/var/www/html/cs257/reichmanj/assignments-user-Muyang/webapp
	scp -r ../webapp/static reichmanj@perlman.mathcs.carleton.edu:/var/www/html/cs257/reichmanj/assignments-user-Muyang/webapp