upload_johnny:
	scp schoogle_api.py reichmanj@perlman.mathcs.carleton.edu:/var/www/html/cs257/reichmanj/assignments-user-Muyang/webapp
	ssh reichmanj@perlman.mathcs.carleton.edu
	cd /var/www/html/cs257/reichmanj/assignments-user-Muyang/webapp


run_johnny:
	python3 schoogle_api.py perlman.mathcs.carleton.edu 5120